[package]
name = "tui-input"
version = "0.9.0"
edition = "2021"
authors = ["Arijit Basu <hi@arijitbasu.in>"]
description = "TUI input library supporting multiple backends"
keywords = ["tui", "terminal", "input"]
repository = "https://github.com/sayanarijit/tui-input"
readme = "README.md"
license = "MIT"
autoexamples = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["crossterm"]
crossterm = ["dep:ratatui"]

[dependencies]
ratatui = { version = "0.28", optional = true }
serde = { version = "1.0.203", optional = true, features = ["derive"] }
termion = { version = "4.0.2", optional = true }
unicode-width = "0.1.13"

[[example]]
name = "crossterm_input"
path = "./examples/crossterm_input.rs"
required-features = ["crossterm"]

[[example]]
name = "termion_input"
path = "./examples/termion_input.rs"
required-features = ["termion"]
